### ISSUE TITLE
How can I use this code in a real robot？

### ISSUE THREAD

**Issue by Mr-Xia-6** [liruiw/OMG-Planner#2]
Forexample baxter，thank you！

**Comment by yuxng** [comment]
The planner will output a trajectory of joint values of the robot arm. Then a controller can be used to control the robot to follow the planned trajectory.

**Comment by Mr-Xia-6** [comment]
> The planner will output a trajectory of joint values of the robot arm. Then a controller can be used to control the robot to follow the planned trajectory.

Yes，I can use this method to solve the planning problem of panda robot in specific situations. However, if I want to test this code in other robot, for example baxter or ur, which part of the code do I mainly need to modify？In Fig. 7 Right)， How can I conbine this code with estimated 6D object poses? Only by combining these two parts can we realize the online grasping planning of the physical robot？  Can you share the code of  estimated 6D object poses?

thank you！

**Comment by liruiw** [comment]
Regarding using OMG with other robots, you can take a look at ycb_render/robotPose/. I store the internal kinematic structures locally but you should be able to write for your own robot. In fact for Franka panda on the pre-generated scenes, you can consider commenting out all KDL dependency and pass  "-g scene" to load the saved goal IKs because only IK depends on KDL. Later for other robots or new scenes, you can replace KDL with moveit, bullet, or other solvers. That would also be a way to work around the tricky KDL installation.

For experiments in the real world, you will need a pose estimator. The entire problem also gets much more complicated when it comes to the real world.
